version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres123@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: faclube
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
